version: '3'
services:
  app:
    build:
      context: ../..
      dockerfile: ./api/java/Dockerfile
    ports:
      - "9001:9001"
    env_file:
      - ../../docker.env
    environment:
      - PUBLIC_DIR_PATH=/public
    command: "/bin/sh"
